### ISSUE TITLE
can't access the course locally after logging in (already purchased it)

### ISSUE THREAD

**Issue by xifengjin88** [epicweb-dev/mcp-fundamentals#27]
I sent an email already but thought I get faster response here. Currently i am stuck at this stage but other than that, the course is great

<img width="1472" height="1093" alt="Image" src="https://github.com/user-attachments/assets/cca68d41-35b3-4ffb-a055-9bcc8576262a" />

**Comment by kentcdodds** [comment]
I've pushed a fix for all the videos, so you should be able to see the videos. We've still got an issue with progress not working quite right just yet though so thank you for your patience as we work on that!

**Comment by xifengjin88** [comment]
<img width="1173" height="743" alt="Image" src="https://github.com/user-attachments/assets/5f3d741c-e840-4d3a-bbcd-c002551c2609" />

after pulling the latest, I see that the ui changed but still can't see the video after logging in

**Comment by kentcdodds** [comment]
And you're logged in locally right?

**Comment by xifengjin88** [comment]
i just clicked login button that takes me to the login page. where I put my email and all that. I have done this for epic react and epic web (long time fan here) and had no trouble

**Comment by kentcdodds** [comment]
You can't see the solution videos but you've purchased the workshop already? You should definitely be able to see the solution videos if you've purchased the workshop. To be clear, you can't see this one for example? https://www.epicai.pro/workshops/epic-mcp-from-scratch-to-production/ping-connect~z2r7d/solution

**Comment by xifengjin88** [comment]
I can't see that video locally but I can see the solution video you shared

**Comment by xifengjin88** [comment]
i can use the 2 together, watch the solution videos on the live page and work on the exercises locally.

**Comment by xifengjin88** [comment]
np! thx!

**Comment by xifengjin88** [comment]
@kentcdodds I lost access to that page and now don't even see any course modules listed at all (not local)

**Comment by xifengjin88** [comment]
ok, will take a break for now, thanks for the update
